spring.application.name=payflow


spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=payflow
spring.datasource.password=payflow_dev_pw
spring.jpa.hibernate.ddl-auto=validate